#pragma once
#include <stdint.h>

// Generated by python/cartpole_lqr_gain.py.
// State order: [cart_position_steps, cart_velocity_steps_s, pole_angle_rad, pole_angle_rate_rad_s]
// Input: signed_step_rate_steps_s target for the cart velocity state.
// Nominal plant: first-order actuator lag; validation also clips cart acceleration.
// Control rate: 250 Hz
// Sample time: 0.004000000 s
// Max command step rate: 12000.000 steps/s
// Actuator time constant: 0.030000000 s
// Actuator alpha: 0.124826681
// Max cart acceleration: 150000.000 steps/s^2
// Max velocity delta/sample: 600.000 steps/s
// Validation command delay: 0.010000000 s
// Track total length: 0.300000 m
// Pole length: 0.130000 m
// Pole rod mass: 0.009500 kg
// Pole tip mass: 0.005000 kg
// Meters per step: 0.000012500 m/step
// Teacher enable gate: |theta| < 3.000 deg and |theta_dot| < 45.000 deg/s
// Teacher disable gate: |theta| < 6.000 deg and |theta_dot| < 90.000 deg/s
// Q diag: [5.333333333e-06, 6.666666667e-07, 1.167220036e+02, 1.621138938e+00]
// R: 1.000000000e-06
// Closed-loop pole magnitudes: [0.841083150, 0.992862607, 0.962884602, 0.962884602]
// Gains: [-2.172154012, -2.726761671, -297368.544923228, -31334.012622122]
// Sign check: +theta -> +u is True, +theta_dot -> +u is True

namespace generated_teacher_lqr {
constexpr uint32_t kControlRateHz = 250U;
constexpr float kSampleTimeSeconds = 0.004000000f;
constexpr float kMaxCommandStepRateStepsPerSecond = 12000.000000000f;
constexpr float kActuatorTimeConstantSeconds = 0.030000000f;
constexpr float kActuatorVelocityAlpha = 0.124826681f;
constexpr float kMaxAccelerationStepsPerSecondSquared = 150000.000000000f;
constexpr float kMaxVelocityDeltaPerSampleStepsPerSecond = 600.000000000f;
constexpr float kValidationCommandDelaySeconds = 0.010000000f;
constexpr float kTrackTotalLengthMeters = 0.300000000f;
constexpr float kPoleLengthMeters = 0.130000000f;
constexpr float kPoleRodMassKg = 0.009500000f;
constexpr float kPoleTipMassKg = 0.005000000f;
constexpr float kMetersPerStep = 0.000012500f;
constexpr float kEnableAngleThresholdRad = 0.052359878f;
constexpr float kEnableAngleRateThresholdRadPerSec = 0.785398163f;
constexpr float kDisableAngleThresholdRad = 0.104719755f;
constexpr float kDisableAngleRateThresholdRadPerSec = 1.570796327f;
constexpr float kQDiag[4] = {0.000005333f, 0.000000667f, 116.722003556f, 1.621138938f};
constexpr float kR = 0.000001000f;
constexpr float kClosedLoopPoleMagnitudes[4] = {0.841083150f, 0.992862607f, 0.962884602f, 0.962884602f};
constexpr float kGains[4] = {-2.172154012f, -2.726761671f, -297368.544923228f, -31334.012622122f};
constexpr bool kPositiveThetaCommandsPositiveStepRate = true;
constexpr bool kPositiveThetaRateCommandsPositiveStepRate = true;
}  // namespace generated_teacher_lqr
