#pragma once
#include <stdint.h>

// Generated by python/cartpole_lqr_gain.py.
// State order: [cart_position_steps, cart_velocity_steps_s, pole_angle_rad, pole_angle_rate_rad_s]
// Input: signed_step_rate_steps_s target for the cart velocity state.
// Nominal plant: first-order actuator lag; validation also clips cart acceleration.
// Control rate: 250 Hz
// Sample time: 0.004000000 s
// Max command step rate: 20000.000 steps/s
// Actuator time constant: 0.030000000 s
// Actuator alpha: 0.124826681
// Max cart acceleration: 300000.000 steps/s^2
// Max velocity delta/sample: 1200.000 steps/s
// Validation command delay: 0.010000000 s
// Track total length: 0.300000 m
// Pole length: 0.130000 m
// Pole rod mass: 0.009500 kg
// Pole tip mass: 0.005000 kg
// Meters per step: 0.000012500 m/step
// Teacher enable gate: |theta| < 3.000 deg and |theta_dot| < 45.000 deg/s
// Teacher disable gate: |theta| < 10.000 deg and |theta_dot| < 150.000 deg/s
// Q diag: [5.333333333e-06, 2.400000000e-07, 1.167220036e+02, 1.621138938e+00]
// R: 1.000000000e-06
// KF Q_proc diag: [0.000000000e+00, 2.500000000e+03, 0.000000000e+00, 2.500000000e-01]
// KF R_obs diag: [4.000000000e+00, 4.000000000e-06]
// KF estimator pole magnitudes: [0.818302570, 0.818302570, 0.843444942, 0.843444942]
// Closed-loop pole magnitudes: [0.861054515, 0.991722921, 0.962938102, 0.962938102]
// Gains: [-2.196651697, -2.585239242, -273589.300038339, -28829.250709474]
// Sign check: +theta -> +u is True, +theta_dot -> +u is True

namespace generated_teacher_lqr {
constexpr uint32_t kControlRateHz = 250U;
constexpr float kSampleTimeSeconds = 0.004000000f;
constexpr float kMaxCommandStepRateStepsPerSecond = 20000.000000000f;
constexpr float kActuatorTimeConstantSeconds = 0.030000000f;
constexpr float kActuatorVelocityAlpha = 0.124826681f;
constexpr float kMaxAccelerationStepsPerSecondSquared = 300000.000000000f;
constexpr float kMaxVelocityDeltaPerSampleStepsPerSecond = 1200.000000000f;
constexpr float kValidationCommandDelaySeconds = 0.010000000f;
constexpr float kTrackTotalLengthMeters = 0.300000000f;
constexpr float kPoleLengthMeters = 0.130000000f;
constexpr float kPoleRodMassKg = 0.009500000f;
constexpr float kPoleTipMassKg = 0.005000000f;
constexpr float kPoleRodCenterOfMassMeters = 0.065000000f;
constexpr float kPoleRodInertiaKgMetersSquared = 0.000053517f;
constexpr float kPoleCenterOfMassMeters = 0.087413793f;
constexpr float kPolePivotInertiaKgMetersSquared = 0.000138017f;
constexpr float kAngleGainRadPerSecSquared = 90.091836735f;
constexpr float kAccelerationCoupling = 9.183673469f;
constexpr float kMetersPerStep = 0.000012500f;
constexpr float kEnableAngleThresholdRad = 0.052359878f;
constexpr float kEnableAngleRateThresholdRadPerSec = 0.785398163f;
constexpr float kDisableAngleThresholdRad = 0.174532925f;
constexpr float kDisableAngleRateThresholdRadPerSec = 2.617993878f;
constexpr float kQDiag[4] = {0.000005333f, 0.000000240f, 116.722003556f, 1.621138938f};
constexpr float kR = 0.000001000f;
constexpr float kKalmanProcessNoiseDiag[4] = {0.000000000f, 2500.000000000f, 0.000000000f, 0.250000000f};
constexpr float kKalmanObservationNoiseDiag[2] = {4.000000000f, 0.000004000f};
constexpr float kKalmanGain[4][2] = {{0.284728175f, 0.356747375f}, {11.652314925f, 27.387988059f}, {0.000000357f, 0.769332842f}, {0.000211941f, 120.292118785f}};
constexpr float kKalmanEstimatorPoleMagnitudes[4] = {0.818302570f, 0.818302570f, 0.843444942f, 0.843444942f};
constexpr float kClosedLoopPoleMagnitudes[4] = {0.861054515f, 0.991722921f, 0.962938102f, 0.962938102f};
constexpr float kGains[4] = {-2.196651697f, -2.585239242f, -273589.300038339f, -28829.250709474f};
constexpr bool kPositiveThetaCommandsPositiveStepRate = true;
constexpr bool kPositiveThetaRateCommandsPositiveStepRate = true;
}  // namespace generated_teacher_lqr
